export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const { companyName, industry, regulationName } = req.body;

    if (!companyName || !industry || !regulationName) {
      res.status(400).json({ error: 'Missing required fields' });
      return;
    }

    const apiKey = process.env.TOGETHER_API_KEY;

    if (!apiKey) {
      res.status(500).json({ error: 'TOGETHER_API_KEY not configured' });
      return;
    }

    const prompt = `You are a regulatory compliance expert. Analyze the impact of this regulation on the company.

COMPANY: ${companyName}
INDUSTRY: ${industry}
REGULATION: ${regulationName}

Return ONLY valid JSON with this structure:
{
  "applicabilityScore": 0-100,
  "applicabilityReasoning": "2 sentences",
  "riskLevel": "critical|high|medium|low",
  "summary": "2 sentence summary",
  "personalizedActionPlan": [
    {
      "step": 1,
      "task": "Specific task",
      "priority": "critical|high|medium|low",
      "estimatedHours": number,
      "aiSuggestedAssignee": "Role name",
      "complianceDeadline": "YYYY-MM-DD",
      "rationale": "Why this matters"
    }
  ],
  "estimatedCosts": {
    "totalHours": number,
    "totalEstimatedCost": number,
    "compliAiAutomationSavings": number
  }
}`;

    const response = await fetch('https://api.together.xyz/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
        messages: [
          { role: 'system', content: 'You are a regulatory compliance AI assistant. Return only valid JSON.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.1,
        max_tokens: 2000
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      res.status(502).json({ error: 'AI API error', details: errorText });
      return;
    }

    const data = await response.json();
    const text = data.choices[0].message.content;
    
    let analysis;
    try {
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        analysis = JSON.parse(jsonMatch[0]);
      } else {
        analysis = JSON.parse(text);
      }
    } catch (e) {
      analysis = {
        applicabilityScore: 75,
        riskLevel: 'high',
        summary: `${regulationName} requires compliance review for ${companyName}.`,
        personalizedActionPlan: [{
          step: 1,
          task: `Review ${regulationName} requirements`,
          priority: 'high',
          estimatedHours: 8,
          aiSuggestedAssignee: 'Compliance Officer',
          complianceDeadline: '2026-06-01',
          rationale: `Initial assessment required for ${industry} companies`
        }],
        estimatedCosts: {
          totalHours: 8,
          totalEstimatedCost: 1200,
          compliAiAutomationSavings: 400
        }
      };
    }

    res.status(200).json({
      ...analysis,
      _meta: {
        aiGenerated: true,
        model: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
        generatedAt: new Date().toISOString(),
        disclaimer: 'This analysis was generated by AI and requires review by qualified legal counsel before implementation. CompliAI does not provide legal advice.',
        requiresHumanApproval: true,
        watermark: '[DRAFT - PENDING HUMAN REVIEW]\nGenerated by AI. Requires human review before use.\nCompliAI does not provide legal advice.'
      }
    });

  } catch (error) {
    console.error('API Error:', error);
    res.status(500).json({ 
      error: 'Internal server error', 
      message: error.message 
    });
  }
}
